-- Catálogos de marcas y categorías.
-- Ejecutar en el SQL Editor de Supabase.

create table if not exists public.marcas (
  id bigint generated by default as identity primary key,
  nombre text unique not null
);

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nombre text unique not null
);

grant select, insert, update, delete on table public.marcas to authenticated;
grant select, insert, update, delete on table public.categorias to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.marcas enable row level security;
alter table public.categorias enable row level security;

drop policy if exists marcas_authenticated_select on public.marcas;
create policy marcas_authenticated_select
on public.marcas
for select
to authenticated
using (true);

drop policy if exists marcas_authenticated_insert on public.marcas;
create policy marcas_authenticated_insert
on public.marcas
for insert
to authenticated
with check (true);

drop policy if exists marcas_authenticated_update on public.marcas;
create policy marcas_authenticated_update
on public.marcas
for update
to authenticated
using (true)
with check (true);

drop policy if exists marcas_authenticated_delete on public.marcas;
create policy marcas_authenticated_delete
on public.marcas
for delete
to authenticated
using (true);

drop policy if exists categorias_authenticated_select on public.categorias;
create policy categorias_authenticated_select
on public.categorias
for select
to authenticated
using (true);

drop policy if exists categorias_authenticated_insert on public.categorias;
create policy categorias_authenticated_insert
on public.categorias
for insert
to authenticated
with check (true);

drop policy if exists categorias_authenticated_update on public.categorias;
create policy categorias_authenticated_update
on public.categorias
for update
to authenticated
using (true)
with check (true);

drop policy if exists categorias_authenticated_delete on public.categorias;
create policy categorias_authenticated_delete
on public.categorias
for delete
to authenticated
using (true);

insert into public.marcas (nombre)
select min(regexp_replace(btrim(marca), '\s+', ' ', 'g'))
from public.productos
where marca is not null and btrim(marca) <> ''
group by lower(regexp_replace(btrim(marca), '\s+', ' ', 'g'))
on conflict (nombre) do nothing;

insert into public.categorias (nombre)
select min(regexp_replace(btrim(categoria), '\s+', ' ', 'g'))
from public.productos
where categoria is not null and btrim(categoria) <> ''
group by lower(regexp_replace(btrim(categoria), '\s+', ' ', 'g'))
on conflict (nombre) do nothing;
