-- Gastos operativos. Ejecutar en el SQL Editor de Supabase.

create table if not exists public.gastos_operativos (
  id bigint generated by default as identity primary key,
  fecha timestamp with time zone default now(),
  concepto text not null,
  moneda text check (moneda in ('USD', 'ARS')),
  monto_original numeric(12, 2) not null,
  cotizacion numeric(12, 2) default 1.00,
  monto_usd numeric(12, 2) not null,
  observaciones text
);

grant select, insert, update, delete on table public.gastos_operativos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.gastos_operativos enable row level security;

drop policy if exists gastos_operativos_authenticated_select on public.gastos_operativos;
create policy gastos_operativos_authenticated_select
on public.gastos_operativos
for select
to authenticated
using (true);

drop policy if exists gastos_operativos_authenticated_insert on public.gastos_operativos;
create policy gastos_operativos_authenticated_insert
on public.gastos_operativos
for insert
to authenticated
with check (true);

drop policy if exists gastos_operativos_authenticated_update on public.gastos_operativos;
create policy gastos_operativos_authenticated_update
on public.gastos_operativos
for update
to authenticated
using (true)
with check (true);

drop policy if exists gastos_operativos_authenticated_delete on public.gastos_operativos;
create policy gastos_operativos_authenticated_delete
on public.gastos_operativos
for delete
to authenticated
using (true);
