-- Conceptos fijos de gastos operativos.
-- Ejecutar en el SQL Editor de Supabase.

create table if not exists public.conceptos_gasto (
  id bigint generated by default as identity primary key,
  nombre text unique not null
);

grant select, insert, update, delete on table public.conceptos_gasto to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.conceptos_gasto enable row level security;

drop policy if exists conceptos_gasto_authenticated_select on public.conceptos_gasto;
create policy conceptos_gasto_authenticated_select
on public.conceptos_gasto
for select
to authenticated
using (true);

drop policy if exists conceptos_gasto_authenticated_insert on public.conceptos_gasto;
create policy conceptos_gasto_authenticated_insert
on public.conceptos_gasto
for insert
to authenticated
with check (true);

drop policy if exists conceptos_gasto_authenticated_update on public.conceptos_gasto;
create policy conceptos_gasto_authenticated_update
on public.conceptos_gasto
for update
to authenticated
using (true)
with check (true);

drop policy if exists conceptos_gasto_authenticated_delete on public.conceptos_gasto;
create policy conceptos_gasto_authenticated_delete
on public.conceptos_gasto
for delete
to authenticated
using (true);

insert into public.conceptos_gasto (nombre)
select min(regexp_replace(btrim(concepto), '\s+', ' ', 'g'))
from public.gastos_operativos
where concepto is not null and btrim(concepto) <> ''
group by lower(regexp_replace(btrim(concepto), '\s+', ' ', 'g'))
on conflict (nombre) do nothing;
