-- Tabla 1: Configuración Global
CREATE TABLE IF NOT EXISTS configuracion (
  id INT PRIMARY KEY DEFAULT 1,
  flete_aereo_usd_kg NUMERIC(10,2) DEFAULT 30.00,
  fee_recepcion_pct NUMERIC(5,2) DEFAULT 3.50,
  fee_giro_pct NUMERIC(5,2) DEFAULT 3.50
);

-- Tabla 2: Productos y Catálogo
CREATE TABLE IF NOT EXISTS productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  marca TEXT DEFAULT 'PUFFCO',
  categoria TEXT DEFAULT 'VAPORIZADOR',
  costo_fob NUMERIC(10, 2) NOT NULL DEFAULT 0,
  peso_kg NUMERIC(10, 3) NOT NULL DEFAULT 0,
  precio_puntero_usd NUMERIC(10, 2) NOT NULL DEFAULT 0,
  precio_distro_usd NUMERIC(10, 2) DEFAULT 0,
  stock_actual INT DEFAULT 0,
  imagen_url TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  precio_kg NUMERIC(10, 2) DEFAULT 0,
  calcular_costo BOOLEAN NOT NULL DEFAULT TRUE,
  costo_total_usd NUMERIC(10, 2),
  incompleto BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla 3: Clientes y Regla de Margen
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT UNIQUE NOT NULL,
  es_distribuidor BOOLEAN DEFAULT FALSE,
  porcentaje_ganancia NUMERIC(5, 2) DEFAULT 100.00,
  email TEXT UNIQUE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  tiene_ficha BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla 4: Pedidos (Cabecera de Ventas)
CREATE TABLE IF NOT EXISTS pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT REFERENCES clientes(id),
  total_venta_usd NUMERIC(10, 2) NOT NULL,
  costo_total_usd NUMERIC(10, 2) NOT NULL,
  ganancia_bruta_usd NUMERIC(10, 2) NOT NULL,
  ganancia_real_usd NUMERIC(10, 2) NOT NULL,
  detalle TEXT,
  observaciones TEXT,
  fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla 5: Detalle del Pedido
CREATE TABLE IF NOT EXISTS detalle_pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT REFERENCES pedidos(id) ON DELETE CASCADE,
  producto_id BIGINT REFERENCES productos(id),
  cantidad INT NOT NULL,
  precio_unitario_cobrado NUMERIC(10, 2) NOT NULL,
  costo_unitario_historico NUMERIC(10, 2) NOT NULL
);

-- Tabla 6: Pagos y Caja
CREATE TABLE IF NOT EXISTS pagos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT REFERENCES clientes(id),
  moneda TEXT CHECK (moneda IN ('USD', 'ARS')),
  monto_original NUMERIC(10, 2) NOT NULL,
  cotizacion NUMERIC(10, 2) DEFAULT 1.00,
  monto_usd_descontado NUMERIC(10, 2) NOT NULL,
  observaciones TEXT,
  pedido_id BIGINT REFERENCES pedidos(id),
  fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
